name: Release (Test)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: macos-12

    steps:
    - uses: actions/checkout@v3

    - name: Download MacPorts
      uses: robinraju/release-downloader@v1.8
      with:
        repository: "macports/macports-base"
        latest: true
        fileName: "*-12-Monterey.pkg"
        out-file-path: "/tmp"
  
    - name: Install MacPorts
      run: sudo installer -pkg /tmp/MacPorts-*.pkg -target /

    - name: Add MacPorts to PATH
      run: echo "/opt/local/bin:/opt/local/sbin" >> $GITHUB_PATH
      
    - name: Install CMake and GCC
      run: sudo port install cmake gcc12 gcc_select
      
    - name: Configure GCC
      run: sudo port select --set gcc mp-gcc12

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
      env:
        CC: '/opt/local/bin/gcc'
        CXX: '/opt/local/bin/g++'

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
